---
# Variables for the web server config

iface: '{{ ansible_default_ipv4.interface }}'

apache_test_message: This is a test -
apache_max_keep_alive_requests: 115
apache_docroot: /var/www/html
apache_config: /etc/httpd/conf/httpd.conf
sites_available: /etc/httpd/sites-available
sites_enabled: /etc/httpd/sites-enabled
apache_dirs:
- "{{ sites_available }}"
- "{{ sites_enabled }}"

lameapp_version: 1.1
