# Playbook targeting hosts with roles
# Multi play playbook
# 3 dashes "---"" signals the start of the doc. Can have any content. E.g. documentation prior to dashes
---
- name: apply the common configuration to all hosts
  order: sorted
  hosts: all
  become: yes
  # Old play level classic roles method
#  roles:
#    - common
  # New (2.4) static import_role task
  tasks:
    - debug:
        msg: "Pre import common role"
    - import_role:
        name: common
    - debug:
        msg: "Post import common role"

- name: apply apache and web roles
  hosts: webservers
  order: reverse_sorted
  become: yes
  roles:
    - apache
    - web
