---
- name: install python bindings for SELinux
  # This way shows each item in output
  yum: name={{ item }} state=present
  loop:
    - libselinux-python
    - libsemanage-python
#  loop_control:
#    loop_var: pkg

#  # yum module allows a list of packages to be installed as one transaction
#  yum:
#    name:
#      - libselinux-python
#      - libsemanage-python
#    state: present

- name: test to see if SeLinux is running
  command: getenforce
  register: sestatus
  changed_when: false
